// Placeholder content for koi-varieties.ts
export const KOI_VARIETIES = [
  'Kohaku',
  'Taisho Sanke',
  'Showa Sanshoku',
  'Shiro Utsuri',
  'Hi Utsuri',
  'Ki Utsuri',
  'Bekko',
  'Aka Bekko',
  'Shiro Bekko',
  'Ki Bekko',
  'Asagi',
  'Shusui',
  'Koromo',
  'Goshiki',
  'Aka Matsuba',
  'Ki Matsuba',
  'Shiro Matsuba',
  'Chagoi',
  'Ochiba Shigure',
  'Soragoi',
  'Karasugoi',
  'Hikari Muji',
  'Hikari Utsuri',
  'Hikari Matsuba',
  'Ogon',
  'Platinum',
  'Yamabuki',
  'Tancho',
  'Ginrin',
  'Doitsu',
  'Tancho Showa',
  'Tancho Sanke',
  'Kikusui',
  'Kumonryu',
  'Benigoi',
  'Kigoi',
  'Kujaku',
  'Kabutogoi',
  'AiKoromo',
  'Budo Goromo',
  'Aragoke',
  'Hikari Nishiki',
  'Hikari Moyo',
  'Other'
];